### PR TITLE
CVSS 4 Scoring Support

### PR DESCRIPTION
**Pull request by brphelps**
## Proposed changes

Add support for CVSS 4.0 (at least base), informed by:
* https://github.com/0llirocks/cvss-suite/issues/32
* https://www.first.org/cvss/calculator/4.0
* https://github.com/FIRSTdotorg/cvss-v4-calculator/tree/main
* https://github.com/pandatix/go-cvss/blob/main/40/cvss40_test.go

Originally I was thinking I would follow the Go code as a model, but looking at the calculator, I think porting the JS to ruby will prove a little simpler.

What I ended up with was something that needed to fork a concept that was baked into the CVSS base classes, basically the need to change how we refer to score "categories" like temporal as being something that is version dependent and not common to all versions. 

I just ended up with "3.1 and before" and "4.0 and later", I think this ends up being a pretty logical way to keep the concepts discrete, but it does mean that some things like the common test methods no longer make sense to be completely reusable across CVSS versions. 

I think one advantage of the porting approach is that making bug fixes can be heavily informed by what the calculator code does and should *very easily* be portable in the future. 

## Types of changes

What types of changes does your code introduce to CvssSuite?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR._

- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by brphelps** [comment]
Hey @[0llirocks](https://github.com/0llirocks) -- this is definitely still just a draft, but I'm exploring with porting the javascript calculator library over. Do you think there is an appetite for getting support for just base / supplemental scores in place in a first pass?   
  
Additionally, does this approach generally seem fine? I have a lot of polish I need to apply, but I was basically doing my best to fit the calculator (and some of the different high level scoring categories) into the existing library. Thanks!

**Comment by 0llirocks** [comment]
Hi  @brphelps, first of all thank you for your PR. So far, everything looks good. As you said, some adjustments here and there but overall a great contribution. So you decided to port the JS calculcator instead of the go project? (Doesn't really matter, I'm just curious)

To be honest I am having some concerns about just adding base and supplemental. This may sound harsh since you are currently doing all the work but I can't publish the gem without supporting all scores, since that's the purpose of the gem. Even if I publish a beta with just base and supplemental, there is no guarentee that this beta will ever be finished. 

Once you are done with your great work, I will still accept the PR whether all scores are implemented or not. But it might end up one a separate branch until it's complete.

I hope this makes sense to you.

**Comment by brphelps** [comment]
@0llirocks that's alright, I understand!  
  
I did end up porting the calculator, from my POV it is much easier to understand the code the closer it is to the calculator and JS and ruby end up looking a bit similar ( with a lot of squinting ).   
  
I'll continue to iterate and see what I can do with the additional environmental scoring, expect to see more on this in the next few days.

**Comment by brphelps** [comment]
@0llirocks -- took a little longer for me to get cycles than I was expecting, but I think I'm ready to start polishing this up and put it out for review. Are there any big changes you're interested in before i take it out of draft? I'm mostly planning on doing a formatting and style pass and seeing if anything can be simplified, but I have been finding the code very easy to debug side by side with the calculator code by having the structure almost entirely mimic what the calculator is doing :thinking: .

**Comment by 0llirocks** [comment]
@brphelps Thank you for your work. Everything looks good at the moment. From my point of you you kept most of the code really close to the existing code, only the calculation is new, which makes it much easier for me to understand what is going on.

Do you think it is possible to also return base, environmental score etc. and not only the overall score? I now that e.g. temporal score doesn't exist anymore but that would increase the compatbility between version 3 and version 4. I am not even sure if this is goal we want to achieve since people always need to check for the version before accessing the scores since cvss 4 offers new scores as well. 

Besides that I will create a new branch for the pr so that we can work on that branch after pr is reviewed and accepted. As you already said, rubocop is not too happy about the styling :D and I think I will also add some more test, especially failing ones. 
Can't wait to see the final result!

**Comment by brphelps** [comment]
@0llirocks I went ahead and took care of most of what I could find rubocop wise. I think it could make sense to tune some of the rubocop configuration since it seems like some of the rules maybe aren't highly valued in the project (looking at the existing exclusions). 

> Do you think it is possible to also return base, environmental score etc. and not only the overall score? I now that e.g. temporal score doesn't exist anymore but that would increase the compatbility between version 3 and version 4. I am not even sure if this is goal we want to achieve since people always need to check for the version before accessing the scores since cvss 4 offers new scores as well.

I did originally take that approach, but I believe that's a fundamental difference in how scores work between 3.1 and 4.0. There don't appear to be individualized scores in 4.0 the same way there is for 3.1, I'm noticing only one roll up score for 4.0 vs. many individual section scores for 3.1: 

image

vs.
 
image

I don't even know if there is a sensible way to try and calculate individual scores and worry about it being confusing if we support something that the spec doesn't really suggest? Open to input or iteration, though!

**Comment by brphelps** [comment]
Alright @0llirocks I think I'm ready for whatever next steps exist -- sounds like folding it into a branch in your repo is the next logical stop?

**Comment by 0llirocks** [comment]
@brphelps Yes, rubocop doesn't have a high priority, especially with all the long vectors, most suggestions make the code less rather than more readable. But I will deal with the rubocop findings (if there are still any).

I just went through the official specification again and I agree, the separate scores are not really mentioned. The only thing I found is

> For some purposes it is useful to have a textual representation of the resulting numeric Base, Threat and Environmental scores.

Maybe @pandatix can help us here? I think for now, we just go with just the overall score. Since the official calculator only has one score, that should be enough :D 

I will merge your pr now and will than work towards the next release of the gem. I will add some more tests and check whether I can still run the gem with ruby 2.6 but gh actions already complains, so let's see. Add release notes, etc.

Overall I think the cvss 4 feature is already in an awesome state and I can release the new version soon (this weekend or next week).

Thank you so much for your contribution, feel free to create a pr for the new branch if there's still something you want to add.

**Comment by pandatix** [comment]
> Originally I was thinking I would follow the Go code as a model, but looking at the calculator, I think porting the JS to ruby will prove a little simpler.

Yup, not a good idea :tada: I optimized the code to reach 0/1-allocs/op so it is not so much readable. I also worked on the JS code, so it is a good take !

> Maybe [me] can help us here? I think for now, we just go with just the overall score. Since the official calculator only has one score, that should be enough :D

Indeed, this is a big change in CVSS v4.0: in previous iterations, the consumers of CVSS vectors had to guess/understand which score to deal with. It put a big overhead on the engineers that had to deal with them.
To avoid this, the new maths (equivalence sets) produce only 1 score, along with a nomenclature that informs on which metrics are being taken into account.
I suggest that the implementation does no less or more: produce 1 score and nomenclature :smile:

**Pull request merged**
